#!/usr/bin/env bash
#  Run Nginx as Nginx 7 lines or less 
apt-get install -y nginx
useradd -r nginx
sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
echo "Nginx is now running as nginx user and listening on all active IPs on port 8080."
