#!/usr/bin/env bash
#Using what you did for task #0, make your fix short n sweet
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
systemctl is-active --quiet nginx || echo "Nginx is not running"
