#!/usr/bin/env bash
# Installing nginx on web-01
sudo apt-get update
sudo apt-get install nginx
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
