#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo sed -i 's/^\(.*listen \)80;/\180;/' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
