#!/usr/bin/env bash
# Installing nginx on web-01
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Holberton School" | sudo tee /var/www/html/index.html

#Testing nginx successfullness
sudo nginx -t

sudo service nginx reload
