#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/alueducation.com permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart
